#Snakefile

# Reading SRR codes 
SRR_codes = open("SRR_Acc_List.txt").read().splitlines()
# Variable for merging:
runs_per_sample = [SRR_codes[i:i+4] for i in range(0, len(SRR_codes), 4)]
# Variables for file/dir names
SAMPLES = range(1, 13)
REPS = range(1,7)
CONDS = ["TB", "NI"]


### Flow start ###

rule all:
    input: 
        "DE_results/DE_results.csv",
        "DE_results/RNA-Seq Graphs.pdf",
        "DE_results/session_info.txt",
        "fastqc_results/full_qc_report_not_trimmed.html",
        "fastqc_results/full_qc_report_trimmed.html"


### Rules ###

### 1. Downloading and merging fastq files

rule get_files:
    output: temp("fastq/{srr}.fastq.gz")
    wildcard_constraints:
        srr = "|".join(SRR_codes)
    conda: "envs/rna_seq.yml"
    shell:
        '''
        echo "Downloading sample: {wildcards.srr}"
        prefetch {wildcards.srr} -O fastq/
        fasterq-dump fastq/{wildcards.srr} --outdir fastq/
        gzip fastq/{wildcards.srr}.fastq
        rm -r fastq/{wildcards.srr}
        '''


rule merge_files:
    input:
        lambda wildcards: expand("fastq/{srr}.fastq.gz", srr = runs_per_sample[int(wildcards.i)-1])
    output:
        temp("fastq/sample_{i}_merged.fastq.gz")
    conda: "envs/rna_seq.yml"
    shell: 
        '''
          echo "Merging sample {wildcards.i}"
          cat {input} > {output}
        '''

### 2. Quality control

rule fastqc_raw:
    input:
        "fastq/sample_{i}_merged.fastq.gz"
    output:
        html = "fastqc_results/not_trimmed/sample_{i}_merged_fastqc.html",
        zip = "fastqc_results/not_trimmed/sample_{i}_merged_fastqc.zip"
    threads: 2
    conda: "envs/rna_seq.yml"
    shell:
        "fastqc -t {threads} -o fastqc_results/not_trimmed {input}"



rule multiqc_raw:
    input:
        expand("fastqc_results/not_trimmed/sample_{i}_merged_fastqc.zip", i=SAMPLES)
    output:
        "fastqc_results/full_qc_report_not_trimmed.html"
    conda: "envs/rna_seq.yml"
    shell:
        "multiqc fastqc_results/not_trimmed -n full_qc_report_not_trimmed -o fastqc_results/"

### 3. Trimming and second Quality Control

rule trimming:
    input: 
        "fastq/sample_{i}_merged.fastq.gz"
    output:
        fastq = "fastq_trimmed/sample_{i}_trimmed.fastq.gz",
        html = "fastq_trimmed/sample_{i}_fastp.html",
        json = "fastq_trimmed/sample_{i}_fastp.json"
    threads: 2
    conda: "envs/rna_seq.yml"
    shell:
        '''
        echo "Trimming sample: {wildcards.i}"
        fastp \
            -w {threads} \
            --in1 "{input}" \
            --out1 "{output.fastq}" \
            --html "{output.html}" \
            --json "{output.json}" \
            --qualified_quality_phred 20 \
            --length_required 40
        '''


rule fastqc_trimmed:
    input:
        "fastq_trimmed/sample_{i}_trimmed.fastq.gz"
    output:
        html = "fastqc_results/trimmed/sample_{i}_trimmed_fastqc.html",
        zip = "fastqc_results/trimmed/sample_{i}_trimmed_fastqc.zip"
    threads: 2
    conda: "envs/rna_seq.yml"
    shell:
         "fastqc -t {threads} -o fastqc_results/trimmed {input}"


rule multiqc_trimmed:
    input:
        expand("fastqc_results/trimmed/sample_{i}_trimmed_fastqc.zip", i=SAMPLES)
    output:
        "fastqc_results/full_qc_report_trimmed.html"
    conda: "envs/rna_seq.yml"
    shell:
        "multiqc fastqc_results/trimmed -n full_qc_report_trimmed -o fastqc_results/"

### 4. Mapping and quantification ###

rule quantification:
    input: 
        "fastq_trimmed/sample_{i}_trimmed.fastq.gz"
    output: 
        directory("salmon_output/sample_{i}_quant")
    threads: 2
    conda: "envs/rna_seq.yml"
    shell:
        '''
        echo "Quantifying sample: {wildcards.i}"

        salmon quant -l A \
            -i references/salmon_index_hg38_49 \
            -r {input} \
            -p {threads} \
            --validateMappings \
            -o {output}
        '''

rule Rename_dir:
    input:
        expand("salmon_output/sample_{i}_quant/quant.sf", i=SAMPLES)
    output:
        expand("salmon_output/rep_{n}_{cond}_quant/quant.sf", n=REPS, cond=CONDS)
    run:
        import os
        n = 1
        for j in range(1, 13, 2):
            os.rename(f"salmon_output/sample_{j}_quant",   f"salmon_output/rep_{n}_TB_quant")
            os.rename(f"salmon_output/sample_{j+1}_quant", f"salmon_output/rep_{n}_NI_quant")
            n += 1


### 5. DE analysis on R

rule rnaseq_analysis:
    input:
        expand("salmon_output/rep_{n}_{cond}_quant/quant.sf", n=REPS, cond=CONDS)
    output:
        "DE_results/DE_results.csv",
        "DE_results/RNA-Seq Graphs.pdf",
        "DE_results/session_info.txt"
    conda:
        "envs/r_DE_analysis.yml"
    script:
        "scripts/DE_analysis.R"



#### Important step outside of the flow:
# Before running the Snakefile:

#run setup.sh