#Snakefile

# Reading SRR codes 
SRR_codes = open("SRR_Acc_List.txt").read().splitlines()
# Variable for merging:
runs_per_sample = [SRR_codes[i:i+4] for i in range(0, len(SRR_codes), 4)]
# Variable for file names
SAMPLES = range(1, 13)


### Flow start ###

rule all:
    input: 
        expand("salmon_output/sample_{i}_quant", i = SAMPLES),
        "fastqc_results/full_qc_report_not_trimmed.html",
        "fastqc_results/full_qc_report_trimmed.html"


## rules:


rule get_files:
    output: temp("fastq/{srr}.fastq.gz")
    shell:
        '''
        prefetch {wildcards.srr} -O fastq/
        fasterq-dump fastq/{wildcards.srr} --outdir fastq/
        gzip fastq/{wildcards.srr}.fastq
        '''


rule merge_files:
    input:
        lambda wildcards: expand("fastq/{srr}.fastq.gz", srr = runs_per_sample[int(wildcards.i)-1])
    output:
        temp("fastq/sample_{i}_merged.fastq.gz")
    shell: 
        '''
          echo "Merging sample {wildcards.i}"
          zcat {input} | gzip > {output}
        '''


rule fastqc_raw:
    input:
        "fastq/sample_{i}_merged.fastq.gz"
    output:
        html = "fastqc_results/not_trimmed/sample_{i}_fastqc.html",
        zip = "fastqc_results/not_trimmed/sample_{i}_fastqc.zip"
    shell:
        "fastqc -t {threads} -o fastqc_results/not_trimmed {input}"
    threads: 2


rule multiqc_raw:
    input:
        expand("fastqc_results/not_trimmed/sample_{i}_fastqc.zip", i=SAMPLES)
    output:
        "fastqc_results/full_qc_report_not_trimmed.html"
    shell:
        "multiqc fastqc_results/not_trimmed -n full_qc_report_not_trimmed -o fastqc_results/"


rule trimming:
    input: 
        "fastq/sample_{i}_merged.fastq.gz"
    output:
        fastq = "fastq_trimmed/sample_{i}_trimmed.fastq.gz",
        html = "fastq_trimmed/sample_{i}_fastp.html",
        json = "fastq_trimmed/sample_{i}_fastp.json"
    shell:
        '''
          fastp \
            -w {threads} \
            --in1 "{input}" \
            --out1 "{output.fastq}" \
            --html "{output.html}" \
            --json "{output.json}" \
            --qualified_quality_phred 20 \
            --length_required 40
        '''
    threads: 2


rule fastqc_trimmed:
    input:
        "fastq_trimmed/sample_{i}_trimmed.fastq.gz"
    output:
        html = "fastqc_results/trimmed/sample_{i}_trimmed_fastqc.html",
        zip = "fastqc_results/trimmed/sample_{i}_trimmed_fastqc.zip"
    shell:
         "fastqc -t {threads} -o fastqc_results/trimmed {input}"
    threads: 2



rule multiqc_trimmed:
    input:
        expand("fastqc_results/trimmed/sample_{i}_trimmed_fastqc.zip", i=SAMPLES)
    output:
        "fastqc_results/full_qc_report_trimmed.html"
    shell:
        "multiqc fastqc_results/trimmed -n full_qc_report_trimmed -o fastqc_results/"


rule quantification:
    input: 
        "fastq_trimmed/sample_{i}_trimmed.fastq.gz"
    output: 
        directory("salmon_output/sample_{i}_quant")
    shell:
        '''
        echo "Quantifying sample: {wildcards.i}"

        salmon quant -l A \
            -i references/salmon_index_hg38_49 \
            -r {input} \
            -p {threads} \
            --validateMappings \
            -o {output}
        '''
    threads: 2




#### Important steps outside of the flow:
# Before running the Snakefile:

#run setup.sh
#conda activate rna_seq


# After running the Snakefile:

#Rename directories from terminal like this:

#n=1
#for ((i=1; i<13; i+=2)); do
#  mv "$HOME/Multi-omics-analysis/01_rnaseq/salmon_output/sample_${i}_quant" "$HOME/Multi-omics-analysis/01_rnaseq/salmon_output/rep_${n}_TB_quant"
#  mv "$HOME/Multi-omics-analysis/01_rnaseq/salmon_output/sample_$((i+1))_quant" "$HOME/Multi-omics-analysis/01_rnaseq/salmon_output/rep_${n}_NI_quant"
#  ((n++))
#done